INSERT INTO dishes (title, description, price, category) VALUES ("Salade nature", "Salade verte, sauce vinaigrette", 4.50,"Salade");
INSERT INTO dishes (title, description, price, category) VALUES ("Salade au noix", "Salade verte, noix, sauve vinaigrette", 6.60,"Salade");
INSERT INTO dishes (title, description, price, category) VALUES ("Salade paysanne", "Lardons, croûtons", 7.50,"Salade");
INSERT INTO dishes (title, description, price, category) VALUES ("Salade savoyarde", "Jambon cru, croûtons, fromage râpé", 7.80,"Salade");
INSERT INTO dishes (title, description, price, category) VALUES ("Soupe à l\'oignon", "Oignons, croûtons", 7.50,"Entree chaude");
INSERT INTO dishes (title, description, price, category) VALUES ("Gratinée à l\'oignon", "Oignons, emmental", 7.70,"Entree chaude");
INSERT INTO dishes (title, description, price, category) VALUES ("Chèvre chaud aux noisettes", "Salade verte, fromage de chèvre, sauce vinaigrette", 9.10,"Entree chaude");
INSERT INTO dishes (title, description, price, category) VALUES ("Saint-Marcelin chaud aux noix", "Salade verte, noix, Saint-Marcelin, sauve vinaigrette", 9.60,"Entree chaude");
INSERT INTO dishes (title, description, price, category) VALUES ("Saucisson sec artisanal", "Origine savoie", 9.60,"Charcuterie");
INSERT INTO dishes (title, description, price, category) VALUES ("Carré de porc séchée", "Origine Savoie", 10.00,"Charcuterie");
INSERT INTO dishes (title, description, price, category) VALUES ("Jambon sec de Savoie", "Origine Savoie, affiné 12 mois", 10.00,"Charcuterie");
INSERT INTO dishes (title, description, price, category) VALUES ("Bacon fumé artisanal", "Origine Savoie", 10.00,"Charcuterie");
INSERT INTO dishes (title, description, price, category) VALUES ("Fondue savoyarde", "Mélange de trois fromages", 18.70,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Fondue suisse", "Gruyère fribourgeois, Vacherin fribourgeois", 21.10,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Raclette fermière au lait cru", "Origine Haute-Savoie, accompagnée de charcuterie", 29.00,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Raclette fumée au lait cru", "Origine Haute-Savoie, accompagnée de charcuterie", 29.50,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Raclette à l'ail des ours au lait cru", "Origine Hautes-Alpes, accompagnée de charcuterie", 30.00,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Tartiflette", "Reblochon fermier, pommes de terre, oignons, lardons, crème fraîche épaisse, salade verte", 15.30,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Gratin de crozets savoyards", "Lardons, crème fraîche épaisse, oignons, fromage râpé, salade verte", 15.30,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Berthoud", "Fromage d'Abondance d'alpage, arrosé au madère et fondu au four", 15.30,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Paillasse de Fribourg", "Galettes de pain mouillées au lait, gruyère suisse, boeuf séché", 16.00,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Diots au vin blanc", "Saucisses purc porc, accompagnés de tomates et de pommes vapeur", 15.10,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Brisgotte", "Pain de campagne, fromage suisse, jambon cru de Savoie, charcuterie, salade verte", 27.00,"Spécialité");
INSERT INTO dishes (title, description, price, category) VALUES ("Mousse au chocolat", "", 6.50,"Dessert");
INSERT INTO dishes (title, description, price, category) VALUES ("Crème au caramel", "", 6.50,"Dessert");
INSERT INTO dishes (title, description, price, category) VALUES ("Salade de fruits frais", "", 6.50,"Dessert");
INSERT INTO dishes (title, description, price, category) VALUES ("Tartelette paysanne aux pommes", "Servie avec une boule de glace à la vanille et de la chantilly", 8.10,"Dessert");
INSERT INTO dishes (title, description, price, category) VALUES ("Fromage blanc à la crème", "", 5.80,"Dessert");
INSERT INTO dishes (title, description, price, category) VALUES ("Fromage blanc aux myrtilles", "", 6.00,"Dessert");